serviceType: NodePort
externalTrafficPolicy: Local
dashboard:
  enabled: true
  domain: traefik.mydomain.xyz # your site domain
  service:
    annotations:
      kubernetes.io/ingress.class: traefik
  auth:
    basic:
      username: "<<your genarated htpasswd>>"
rbac:
  enabled: true
deployment:
  hostPort:
    httpEnabled: true
    httpsEnabled: true
# helm install --name my-traefik --namespace kube-system --values traefik.yaml stable/traefik
