serviceType: NodePort
externalTrafficPolicy: Local
ssl:
  enabled: true
  enforced: true
  permanentRedirect: true
dashboard:
  enabled: true
  domain: example.mydomain.xyz # your site domain
  service:
    annotations:
      kubernetes.io/ingress.class: traefik
  auth:
    basic:
      username: $apr1$ks/R6T8d$9eqHzVLuGGTYVifFgGOSG0
rbac:
  enabled: true
deployment:
  hostPort:
    httpEnabled: true
    httpsEnabled: true
# helm install --name my-traefik --namespace kube-system --values traefik.yaml stable/traefik
